// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIhPmDXK1vzya9lMcWoz9c5qApXP9H9wQ',
    appId: '1:267091699106:web:db4f3e4fe365ab8a9d3efb',
    messagingSenderId: '267091699106',
    projectId: 'food-9a095',
    authDomain: 'food-9a095.firebaseapp.com',
    storageBucket: 'food-9a095.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtmdTWjdYcYFVGT-5MsQJo6yBWk3QIU1Q',
    appId: '1:267091699106:android:e2d87ebe40382e9d9d3efb',
    messagingSenderId: '267091699106',
    projectId: 'food-9a095',
    storageBucket: 'food-9a095.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYsXLkvcyKfwpU3djm_lvChnDcosBq4ZQ',
    appId: '1:267091699106:ios:0af3dd28b9282d959d3efb',
    messagingSenderId: '267091699106',
    projectId: 'food-9a095',
    storageBucket: 'food-9a095.firebasestorage.app',
    iosClientId:
        '267091699106-ftin674etv75t38ft2ohf97rssrbvekr.apps.googleusercontent.com',
    iosBundleId: 'com.misawa.food.foodApp',
  );
}
